stages:
  - build
  - test
job1:
  stage: build
  tags: 
    - windows
  script: 
    - chcp 65001
    - "dotnet build --source http://nuget.cd.xunmei.com/nuget/Default"

job2:
  stage: test
  tags:
    - windows
  script: 
    - chcp 65001
    - dotnet restore --source http://nuget.cd.xunmei.com/nuget/Default
    - dotnet test --no-restore Test\\Test.csproj /p:CollectCoverage=true
  coverage: /Web\s*\|\s*([\d\.]+)/